<?php namespace App\Models;

use CodeIgniter\Model;

class PostModel extends Model
{
    /**
     * table name
     */
    protected $table = "product";

    /**
     * allowed Field
     */
    protected $allowedFields = ['REQUEST_ID','ISSUING_BANK', 'ADVISING_BANK','APPLICANT','BENEFICIARY','PORT_OF_LOADING','PORT_OF_DISCHARGE','PLACE_OF_TAKING_IN_CHARGE','PLACE_OF_DESTINATION','DESCRIPTION_OF_GOOODS','COUNTRY_OF_ORIGIN','SHIPPER','NOTIFY_PARTY','CONSIGNEE','VESSEL_PRE_CARRIAGE','VESSEL_MAIN_VESSEL','CARRIER','MASTER','CHARTERER','OWNER','AGENT_OF_CARRIER','DELIVERY_AGENT_IN_TRANSPORT_DOC','SHIPPING_COMPANY','INSURANCE_COMPANY','AGENT_OF_INSURANCE_COMPANY','SETTLING_AGENT_OF_INSURANCE','ISSUER_OF_CERT_OF_ANALYSIS','ISSUER_OF_PACKING_LIST','ISSUER_OF_HEALTH_CERTIFICATE','MANUFACTURER','OTHERS','XML_SOAP_REQ','XML_SOAP_RSP','STATUS','USER_ID','CREATED_TIMESTAMP'];
}